name: Secret Scanning with TruffleHog

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Run TruffleHog Secret Scan
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: >-
          --results=verified,unknown
          --json
          --log-level=2
      
    - name: Comment on PR (if secrets found)
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Secret Scanning Failed!** TruffleHog found potential secrets in this PR. Please review the logs and remove any sensitive information before merging.'
          })